services:
  - type: web
    name: financeee-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js

  - type: web
    name: financeee-ai
    env: python
    buildCommand: cd ai && pip install -r requirements.txt
    startCommand: cd ai && gunicorn app:app